version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
        - "*"
    labels:
      - "dependencies"
    target-branch: "master"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "[workflow]"
    labels:
      - "dependencies"
    target-branch: "master"
